[project]
name = "lic-dsf"
version = "0.0.1"
description = "A Python library encapsulating the logic of the IMF's LIC DSF (Low-Income Country Debt Sustainability Framework) template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
